

#include "main.h"
#include "I2C_Init.h"
#include "TMP102.h"
#include "TESTING_CONDITIONS.h"
#include "Delay_Function.h"
#include "LED_Blink.h"
#include "Table_State_Machine.h"
#include "Logger.h"

#define TIMER_COUNT  4

//enum for all the states achieved in the state machine 1
enum states{

POST_TEST,
READING_TEMPERATURE,//READ THE TEMPERATURE VALUE 					->COMPLETE/ALERT/DISCONNECT
COMPLETE_AVERAGE_TEMPERATURE,//DISPLAY THE AVERAGE TEMPERATURE		->TIMEOUT3/TIMEOUT4
DISCONNECT,//DISCONNECT WHEN SENSOR IS NOT RESPONDING
ALERT,//ALERT FROM MASTER WHEN TEMPERATURE BECOMES NEGATIVE			->COMPLETE/DISCONNECT
TIMEOUT_THREE_COUNT,//BACK TO THE TEMPERATURE READING FUNCTION		->COMPLETE(AVERAGE)
TIMEOUT_FOUR_COUNT//AFTER COUNT 4 TRANSIT TO THE STATE MACHINE 2	->STATEMACHINE2

};



void State_Machine();
